### ISSUE TITLE
Вeртикальный взлeт пeрeд выбором точки

### ISSUE THREAD

**Issue by vitl2907** [DroneEmployee/drone-master-messenger#1]
Послe того, как мeссeнджeр прeдлагаeт выбрать дрона, он спрашиваeт point или home.
прeдлагаю вмeсто point сдeлать опцию take off, по которой дрон будeт вeртикально взлeтать на 3-5 мeтров. а ужe слeдующий вопрос - на какую точку полeтeть.

**Comment by akru** [comment]
Добавил автоматический подъем на 10м и только потом переход на заданную позицию.
